version: '3.8'
services:

  core:
    environment:
      - PUID
      - PGID
    image: serversideup/php:8.1-fpm-nginx
    networks:
      - candil
      - database
      - traefik
    restart: always
    volumes:
      - .:/var/www/html/:cached
    working_dir: /var/www/html

networks:
  candil:
  database:
    external: true
  traefik:
    external: true
