version: '3.8'
services:

  core:
    environment:
      - SSL_MODE=off
      - PHP_SESSION_COOKIE_SECURE=false
      - DEBUG_OUTPUT=true
      - S6_VERBOSITY=5
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.candil.entrypoints=web"
      - "traefik.http.routers.candil.rule=Host(`candil.localhost`)"
      - "traefik.http.routers.candil.service=candil"
      - "traefik.http.services.candil.loadbalancer.server.port=80"

  mailhog:
    image: mailhog/mailhog
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.candil-mailhog.entrypoints=web"
      - "traefik.http.routers.candil-mailhog.rule=Host(`candil-mailhog.localhost`)"
      - "traefik.http.routers.candil-mailhog.service=candil-mailhog"
      - "traefik.http.services.candil-mailhog.loadbalancer.server.port=8025"
    networks:
      - candil
      - database

  node:
    command: "npm run dev"
    environment:
      - NODE_ENV=production
    image: node:lts
    networks:
      - candil
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
